### PR TITLE
Fixes #8, #9 - Fixed regex for floating point numbers

### LINKED ISSUE #8: Floating point exponent notation
the following notations are unrecognized by ritchie:
```
f1 = 1.0e3
f2 = 2.0E4
f3 = 3.0E-6
f4 = 4.0e+2
```
Expected results are:
```
f1 = 1000.000000
f2 = 20000.000000
f3 = 0.000003
f4 = 400.000000
```

### PR DESCRIPTION
**Pull request by DhavalKapil**

### CODE REVIEW

**Comment by DhavalKapil** [comment]
Updated patch by merging recent changes.

**Comment by rrezel** [comment]
```
a = 1.0e+1
b = 1.0e-1
c = 5e+2
d = 6e-1
```

All except `a` fails.

The above test case fails where `e` is followed by a negative value or where the

**Comment by DhavalKapil** [comment]
The first two were passing earlier.
Now `a`, `b`, `c` and `d` all are passing.

**Comment by rrezel** [comment]
It works now. Thanks!

**Pull request merged**
